// <auto-generated />
using System;
using Estetica.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estetica.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estetica.Domain.Entities.Cabina", b =>
                {
                    b.Property<int>("CabinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CabinaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CabinaId");

                    b.ToTable("Cabinas");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarritoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CarritoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ConversacionIA", b =>
                {
                    b.Property<int>("ConversacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversacionId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConversacionesIA");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Cupon", b =>
                {
                    b.Property<int>("CuponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuponId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("CuponId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.DiagnosticoPiel", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiagnosticoId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoPielId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("DiagnosticoId");

                    b.HasIndex("TipoPielId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DiagnosticosPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Fidelizacion", b =>
                {
                    b.Property<int>("FidelizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FidelizacionId"));

                    b.Property<int>("EstampitasActuales")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("FidelizacionId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Fidelizaciones");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.HistorialTratamiento", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialesTratamiento");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ItemCarrito", b =>
                {
                    b.Property<int>("ItemCarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemCarritoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CarritoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("ItemCarritoId");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsCarrito");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("NotificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("OrdenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrdenesCompra");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("integer");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("PagoId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ProductoTipoPiel", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPielId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId", "TipoPielId");

                    b.HasIndex("TipoPielId");

                    b.ToTable("ProductosTiposPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Profesional", b =>
                {
                    b.Property<int>("ProfesionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfesionalId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ProfesionalId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.QrToken", b =>
                {
                    b.Property<int>("QrTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QrTokenId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("QrTokenId");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("QrTokens");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ServicioId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.TipoPiel", b =>
                {
                    b.Property<int>("TipoPielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoPielId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipoPielId");

                    b.ToTable("TiposPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("CabinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("TurnoId");

                    b.HasIndex("CabinaId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.TurnoServicio", b =>
                {
                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.HasKey("TurnoId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("TurnosServicios");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Carrito", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ConversacionIA", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ConversacionesIA")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Cupon", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cupones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.DiagnosticoPiel", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.TipoPiel", "TipoPiel")
                        .WithMany("DiagnosticosPiel")
                        .HasForeignKey("TipoPielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DiagnosticosPiel")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPiel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Fidelizacion", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Fidelizacion")
                        .HasForeignKey("Estetica.Domain.Entities.Fidelizacion", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.HistorialTratamiento", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Profesional", "Profesional")
                        .WithMany("HistorialesTratamiento")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Turno", "Turno")
                        .WithMany("HistorialesTratamiento")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialesTratamiento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");

                    b.Navigation("Turno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ItemCarrito", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Carrito", "Carrito")
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Producto", "Producto")
                        .WithMany("ItemsCarrito")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("OrdenesCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.OrdenCompra", "OrdenCompra")
                        .WithMany("Pagos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Estetica.Domain.Entities.Turno", "Turno")
                        .WithMany("Pagos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrdenCompra");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.ProductoTipoPiel", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Producto", "Producto")
                        .WithMany("ProductoTiposPiel")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.TipoPiel", "TipoPiel")
                        .WithMany("ProductoTiposPiel")
                        .HasForeignKey("TipoPielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("TipoPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Profesional", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Profesional")
                        .HasForeignKey("Estetica.Domain.Entities.Profesional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.QrToken", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Pago", "Pago")
                        .WithOne("QrToken")
                        .HasForeignKey("Estetica.Domain.Entities.QrToken", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Turno", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Cabina", "Cabina")
                        .WithMany("Turnos")
                        .HasForeignKey("CabinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Profesional", "Profesional")
                        .WithMany("Turnos")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Turnos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabina");

                    b.Navigation("Profesional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.TurnoServicio", b =>
                {
                    b.HasOne("Estetica.Domain.Entities.Servicio", "Servicio")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estetica.Domain.Entities.Turno", "Turno")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Cabina", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Carrito", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Pago", b =>
                {
                    b.Navigation("QrToken");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesOrden");

                    b.Navigation("ItemsCarrito");

                    b.Navigation("ProductoTiposPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Profesional", b =>
                {
                    b.Navigation("HistorialesTratamiento");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.TipoPiel", b =>
                {
                    b.Navigation("DiagnosticosPiel");

                    b.Navigation("ProductoTiposPiel");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Turno", b =>
                {
                    b.Navigation("HistorialesTratamiento");

                    b.Navigation("Pagos");

                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("Estetica.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("ConversacionesIA");

                    b.Navigation("Cupones");

                    b.Navigation("DiagnosticosPiel");

                    b.Navigation("Fidelizacion");

                    b.Navigation("HistorialesTratamiento");

                    b.Navigation("Notificaciones");

                    b.Navigation("OrdenesCompra");

                    b.Navigation("Profesional");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
